### ISSUE TITLE
Web UI search broken for certain common terms

### ISSUE THREAD

**Issue by ctz** [ewxrjk/disorder#57] opened 2016-01-14 16:42 UTC
When searching for terms like 'red' I get the following page contents:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<!--
This file is part of DisOrder.
Copyright (C) 2004-2008 Richard Kettlewell

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<html>
 <head>
  <link rel=stylesheet
        type="text/css"
        href="
```

That's the whole page, and predictably renders blank. The HTTP response is 200 OK. Presumably the CGI is crashing somewhere. Searches with less common terms work OK.

Version is '5.0.dev' built from mdw's gstreamer branch.

Cheers,
Joe

**Comment by distorted-mdw** [comment] 2016-01-15 20:44
I can reproduce this.  The CGI program is aborting due to an assertion
failure somewhere in the guts of **malloc**, so it seems like there's a
heap corruption.

    disorder: malloc.c:3096: sYSMALLOc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 * (sizeof(size_t))) - 1)) & ~((2 * (sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long)old_end & pagemask) == 0)' failed.

Once the bug can be reproduced against a debug build, **valgrind** spots
the problem really quickly.

    ==4916== Invalid write of size 1
    ==4916==    at 0x8052C61: cgi__input (cgi.c:78)
    ==4916==    by 0x8052DFA: cgi__init_multipart (cgi.c:130)
    ==4916==    by 0x8052F21: cgi__init_post (cgi.c:154)
    ==4916==    by 0x8052FC6: cgi_init (cgi.c:178)
    ==4916==    by 0x80524B2: main (cgimain.c:43)
    ==4916==  Address 0x442e93c is 0 bytes after a block of size 404 alloc'd
    ==4916==    at 0x4028308: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
    ==4916==    by 0x805D554: xmalloc_noptr (mem.c:138)
    ==4916==    by 0x8052BA3: cgi__input (cgi.c:64)
    ==4916==    by 0x8052DFA: cgi__init_multipart (cgi.c:130)
    ==4916==    by 0x8052F21: cgi__init_post (cgi.c:154)
    ==4916==    by 0x8052FC6: cgi_init (cgi.c:178)
    ==4916==    by 0x80524B2: main (cgimain.c:43)

And, behold, at that very line is an explicit write of a zero byte one
past the end of the allocated buffer.  A little archæology reveals that
the bug has been there since the **lib/cgi.c** was created, and in fact
was copied there from the earlier **server/cgi.c**, where it's been ever
since the import from Arch.

Fortunately this is an easy fix.

    diff --git a/lib/cgi.c b/lib/cgi.c
    index 9fd42f1..023c5bb 100644
    --- a/lib/cgi.c
    +++ b/lib/cgi.c
    @@ -75,7 +75,7 @@ static void cgi__input(char **ptrp, size_t *np) {
       }
       if(memchr(q, 0, n))
	 disorder_fatal(0, "null character in request body");
    -  q[n + 1] = 0;
    +  q[n] = 0;
       *ptrp = q;
       if(np)
	 *np = n;

I've committed this patch as 751b34ac... which is on `mdw/master'.  I'm
going to test things a bit, and then merge these pending changes to
`master' over the weekend.

**Comment by distorted-mdw** [comment] 2016-01-16 01:31
OK, this is now merged, so I'm closing the bug.

**Closed by distorted-mdw** 2016-01-16 01:31 UTC
Labels: bug
